# Generated by Django 3.2 on 2021-04-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.experiment')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField(default=None)),
                ('unit', models.CharField(max_length=200)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.experiment')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.experiment')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sample')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sample'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=200)),
                ('file_delimiter', models.CharField(max_length=200)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.experiment')),
            ],
        ),
    ]
