# Generated by Django 3.2 on 2021-04-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='csv',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
