# Generated by Django 3.2 on 2021-04-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data_file_delimiter',
            new_name='file_delimiter',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='data_file_name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='data_file_type',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='data_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='data_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='experiment_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='parameter_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='parameter_unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='parameter_value',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='step',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
