# Generated by Django 3.2 on 2021-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_file_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='csv_plot',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_delimiter',
            field=models.CharField(blank=True, choices=[('\t', 'tabstop'), ('.', '.'), (',', ','), (';', ';')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
