# Generated by Django 3.2 on 2021-04-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210412_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_text',
            new_name='text',
        ),
    ]
