# Generated by Django 3.2 on 2021-04-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210416_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.experiment'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.sample'),
        ),
        migrations.AlterField(
            model_name='note',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_note', to='polls.experiment'),
        ),
        migrations.AlterField(
            model_name='note',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_note', to='polls.sample'),
        ),
        migrations.AlterField(
            model_name='note',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_note', to='polls.step'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_parameter', to='polls.experiment'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_parameter', to='polls.sample'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_parameter', to='polls.step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.experiment'),
        ),
        migrations.AlterField(
            model_name='step',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.sample'),
        ),
    ]
