# Generated by Django 3.2 on 2021-04-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210411_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='parameter_value',
            field=models.FloatField(default=None),
        ),
    ]
