# Generated by Django 3.2 on 2021-04-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210416_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='sample',
        ),
        migrations.AlterField(
            model_name='data',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.experiment'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='polls.sample'),
        ),
        migrations.AlterField(
            model_name='note',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_notes', to='polls.experiment'),
        ),
        migrations.AlterField(
            model_name='note',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_notes', to='polls.sample'),
        ),
        migrations.AlterField(
            model_name='note',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_notes', to='polls.step'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_parameters', to='polls.experiment'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_parameters', to='polls.sample'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_parameters', to='polls.step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_steps', to='polls.experiment'),
        ),
    ]
