# Generated by Django 3.2 on 2021-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210426_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
