# Generated by Django 3.2 on 2021-04-21 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210420_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date of experiment'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
