# Generated by Django 3.2 on 2021-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210422_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='experiment/files/'),
        ),
        migrations.AlterField(
            model_name='data',
            name='file_delimiter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
