# Generated by Django 3.2 on 2021-04-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210422_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, choices=[('txt', 'txt'), ('csv', 'csv'), ('img', 'image'), ('etc', 'other')], max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='experiment/files/')),
                ('file_delimiter', models.CharField(blank=True, choices=[('\t', 'tag'), ('dot', '.'), ('comma', ','), ('semicolon', ';')], max_length=200, null=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_data', to='polls.experiment')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_name', to='polls.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.FileField(upload_to='')),
                ('img', models.ImageField(upload_to='')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_plots', to='polls.file')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_plots', to='polls.sample')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
